# clef de haut niveau (qui crée un conteneur)
services:

  back:
    build: ./backend
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    environment:
      TGC_DBPASS: example

  front:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/webapp

# sous clef pour créer service/conteneur db
  db:
    image: postgres:16
    # le mode always va toujours relancer alors que unless-stopped laisse le user stopper son conteneur
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
    # :Dossier de données propre à postgres
      - /c/Users/ce pc/quests/ALTERNANCE/the-good-corner-db-data:/var/lib/postgresql/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
    # technique de configuration imposée par postgres
      POSTGRES_PASSWORD: example
    # exposer un port pour rendre le conteneur accessible
    ports:
      - 5432:5432

# service pour parcourir en mode web une base de données 
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080