# clef de haut niveau (qui crée un conteneur)
# Les conteneurs sont automatiquement liés 
services:

# sous clef pour créer service/conteneur db
  db:
    image: postgres:16
    # le mode always va toujours relancer alors que unless-stopped laisse le user stopper son conteneur
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
    # technique de configuration imposée par postgres
      POSTGRES_PASSWORD: example

# service pour parcourir en mode web une base de données 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080