import Head from "next/head";
import { ReactNode } from "react";
import Header from "./Header";

function Layout({ children }: { children: ReactNode }) {
    return (
        <>
            <Head>
                <title>Create next app</title>
                <meta name="decription" content="Generated by Next app" />
                <meta name="viewport" content="width=device-width, initual-scale=1" />
            </Head>
            <Header />
            <main className="main-content">{children}</main>
        </>
    );
}

export default Layout;