GET http://localhost:4000/

### Apollo queries
### Get all cats
POST http://localhost:4000/ 
Content-Type: application/json

{
    "query": "query QueryAllCategories { getAllCategories { name } }"
}

### Create user
POST http://localhost:4000/ 
Content-Type: application/json

{
    "query": "mutation 
    CreateUser($email: String!, $password: String!, $role: String!) 
    { createUser { email: $email password: $password role: $role } }",
    "variables": {
        "email": "florence.buchelet@gmail.com",
        "password": "example",
        "role": "USER"
        }
}

### Login and JWT
POST http://localhost:4000/
Content-Type: application/json

{
    "query": "query LoginUser($email: String!, $password: String!) { login(email: $email, password: $password) }",
    "variables": {
        "email": "yetanotheruser@user.user",
        "password": "example"
    }
}

### Get all ads

GET http://localhost:4000/ads

### Get all ads for a specific city

GET http://localhost:4000/ads?city=Bordeaux

### Get all ads for a specific category

GET http://localhost:4000/ads?category=2

### All categories

GET http://localhost:4000/categories

### Delete an ad

DELETE http://localhost:4000/ads/3

### Add a star

PUT http://localhost:4000/ads/1/star


### Filter multiple categories

GET http://localhost:4000/ads/category
Content-Type: application/json

[
    "voiture", "autre"
]

### Average price in a category

GET http://localhost:4000/ads/category/average

### 

GET http://localhost:4000/ads/search
Content-Type: application/json

{
    "prompt": "thom"
}

### Add an ad
POST http://localhost:4000/ads
Content-Type: application/json

{
    "id": 1,
    "title": "rollers",
    "description":
        "My roller is blue, working fine. I'm selling it because I've got a new one",
    "owner": "roller.seller@gmail.com",
    "price": 10,
    "picture":
        "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Lille",
    "createdAt": "2023-09-05T10:13:14.755Z"
}

### Delete an ad

DELETE http://localhost:4000/ads
Content-Type: application/json

{
    "id": 1
}

### Update an ad
PUT http://localhost:4000/ads
Content-Type: application/json

{
    "id": 2,
    "newAd": {
        "id": 2,
        "title": "rolLLLLLlers",
        "description":
            "My roller is blue, working fine. I'm selling it because I've got a new one",
        "owner": "roller.seller@gmail.com",
        "price": 10,
        "picture":
            "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
        "location": "Lille",
        "createdAt": "2023-09-05T10:13:14.755Z"
        }
}

### SECOND TOPIC

GET http://localhost:4000/movies/count
Content-Type: text/plain

###

GET http://localhost:4000/movies/totalBudget
Content-Type: text/plain

###

GET http://localhost:4000/movies?minYear=2010
Content-Type: text/plain

###

GET http://localhost:4000/movies?requestedTime=11:30
Content-Type: text/plain

###